
// HOW MANY VECTORS
#define K_LEN 8

// HOW MANY WORDS IN A VECTOR
#define K_WORDS 8

#define SECRET_PAIRS_N 2048

// DO QUAL DERIVAREMOS O SECRET
#define PASSWORD_SIZE_MIN    16
#define PASSWORD_SIZE_MAX 65536

//
#define PASSWORD_ROUNDS 16
