
// HOW MANY WORDS IN A PAIR
#define K_LEN2 64

#define SECRET_PAIRS_N 2048

// DO QUAL DERIVAREMOS O SECRET
#define PASSWORD_SIZE_MIN    16
#define PASSWORD_SIZE_MAX 65536

//
#define PASSWORD_ROUNDS 16
