
// HOW MANY WORDS IN A KEY
#define K_LEN 64

// THE SIZE, IN BYTES
#define K_SIZE 512

// HOW MANY KEYS IN A SECRET
#define SECRET_KEYS_N 2048

#define SECRET_SIZE (SECRET_KEYS_N * K_LEN * sizeof(u64))

// DO QUAL DERIVAREMOS O SECRET
#define PASSWORD_SIZE_MIN    16
#define PASSWORD_SIZE_MAX 65536

//
#define PASSWORD_ROUNDS 16
