
// HOW MANY WORDS IN A KEY
#define K_LEN 8

// THE SIZE, IN BYTES
#define K_SIZE 64

// HOW MANY KEYS IN A SECRET
#define SECRET_KEYS_N 16384

//
#define SECRET_SIZE 1048576

// DO QUAL DERIVAREMOS O SECRET
#define PASSWORD_SIZE_MIN     16
#define PASSWORD_SIZE_MAX 524288

//
#define PASSWORD_ROUNDS 16

//
BUILD_ASSERT(SECRET_SIZE == (SECRET_KEYS_N * K_LEN * sizeof(u64)));
