
// KEYS                     SENDER'S IKEYS BEING TAUGHT (UNDEFINED ON PONG)
// RANDOM | VER             SENDER'S IKEYS INDEX BEING REGISTERED (UNDEFINED ON PONG)
// TIME                     SENDER'S TIME (RAW)
#define PING_SIZE 80

// KEYS, VERSION
#define PING_RANDOMS_N 9

// NOTE: AO ENVIAR UM PONG, O PKT->COUNTER É O RCOUNTER SENDO RESPONDIDO

#define PKT_PING_K(pkt)     (pkt->p + PKT_ALIGN_RANDOMS)
#define PKT_PING_VER(pkt)   (pkt->p[PKT_ALIGN_RANDOMS + K_LEN])
#define PKT_PING_TIME(pkt)  (pkt->p[PKT_ALIGN_RANDOMS + K_LEN + 1])
