
#define PING_SIZE (PING_RANDOMS_N * sizeof(u64))
#define PONG_SIZE (PONG_RANDOMS_N * sizeof(u64))

#define PING_RANDOMS_N (K_LEN + 1)
#define PONG_RANDOMS_N 8

// PING PACKET PAYLOAD: KEYS ... RANDOM ... 8-BIT VERSION ... RANDOM
#define PING_VERSION_OFFSET (PING_SIZE - 4)

BUILD_ASSERT(PING_SIZE != PONG_SIZE);
