
#define PING_SIZE 80

// KEYS, VERSION
#define PING_RANDOMS_N 9

#define PING_INDEX_K   0 // K_LEN
#define PING_INDEX_VER 8 // SENDER'S IKEYS INDEX BEING REGISTERED (UNDEFINED ON PONG)
#define PING_INDEX_CTR 9 // SENDER'S LCOUNTER

// NOTE: AO ENVIAR UM PONG, O PKT->COUNTER É O RCOUNTER SENDO RESPONDIDO
