
// COMMANDS
enum CMDS {
    CMD_PATH_ON,
    CMD_PATH_OFF,
    CMD_PATH_PRINT,
    CMD_PATH_PHYS_SET,
    CMD_PATH_PHYS_CLR,
    CMD_PATH_ENCAP_RAW,
    CMD_PATH_ENCAP_ETH,
    CMD_PATH_ENCAP_ETH_VLAN,
    CMD_PATH_ENCAP_ETH_VLAN_PPP,
    CMD_PATH_ENCAP_ETH_VLAN_PPP_SESSION,
    CMD_PATH_ENCAP_ETH_PPP,
    CMD_PATH_ENCAP_ETH_PPP_SESSION,
};

struct cmd_s {

};
