
CFLAGS_clf.o += -Wfatal-errors
CFLAGS_clf.o += -Werror
CFLAGS_clf.o += -Wall
CFLAGS_clf.o += -Wextra
CFLAGS_clf.o += -Wno-declaration-after-statement
CFLAGS_clf.o += -Wno-missing-declarations
CFLAGS_clf.o += -Wno-missing-prototypes
CFLAGS_clf.o += -Wno-error=sign-compare
CFLAGS_clf.o += -Wno-error=unused-parameter
CFLAGS_clf.o += -Wno-error=unused-function
CFLAGS_clf.o += -Wno-error=unused-label
CFLAGS_clf.o += -Wno-error=unused-variable
CFLAGS_clf.o += -Wno-error=date-time
CFLAGS_clf.o += -Wno-type-limits
CFLAGS_clf.o += -Wno-unused-parameter

CFLAGS_clf.o += -Wno-sign-compare

# -moutline-atomics
# -mno-outline-atomics

obj-$(CONFIG_CLF) += clf.o
